# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1cd1999878faaaa7fc96c76d2aa0db4829c1b16c0bb7470ed33fe9e3f0b9a1924fb0977ba78b6945da6e39f39980141779642a919ee9454894f10b18e04ef954

test:
  secret_key_base: 93f709d7fa6774944085387647551462cc3422ea5cac873cb49939eec47d98b7a32b26a7e5f0f8fdd9037505c6e073b48bfa1d706f4ef4b4f4ad9f4c123b304e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
